# Generated by Django 2.2.15 on 2020-08-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200807_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hjkhgkjhkjhkj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hjgfhjgjhg', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
