# Generated by Django 2.2.15 on 2020-08-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_hjkhgkjhkjhkj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hgfhgfhgf',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='hjgjhgjhghjg',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='kjhkjhkjh',
        ),
    ]
